# Reference-project: https://github.com/NorthernBUG/northernbug.github.io

title: FCC Certification Projects | Juan Diaz
author: Juan Pablo Diaz
email: contact@jpdiaz.dev
url: https://jpdiaz.dev

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This repository contains all the projects completed to earn freeCodeCamp
  certifications. Each folder corresponds to a specific certification and
  includes a link to the related project repos.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  # - jekyll-redirect-from
  # - jekyll-paginate
  # - tag-page-generator
  # - jekyll-minifier
  # - jekyll-remote-include
  # - faraday-retry

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - FullStackDeveloper/FullStackDeveloper.md
  - LegacyJavaScriptAlgorithmsAndDataStructures/JsAlgorithmsAndData.md

  # - FullStackDeveloper/Html/README.md
  # - FullStackDeveloper/Css/README.md
  # - FullStackDeveloper/Js/README.md

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic

  # Set to `true` to show excerpts on the homepage.
  #show_excerpts: false

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # social links
twitter_username: JuanDiaz_427
github_username: juanPabloDiaz
linkedin_username: 1diazdev
# youtube_username: jekyll

# generate social links in footer
# social_links:
#   github: juanPabloDiaz
#   linkedin: 1diazdev
#   twitter: JuanDiaz_427
