title: Full Stack Developer FCC | Juan Diaz
description: This repository contains all the projects completed to earn freeCodeCamp certifications. Each folder corresponds to a specific certification and includes a link to the related project repos.
theme: jekyll-theme-cayman
